import Head from 'next/head'
import Navigation from '@/components/Navigation'
import Landing from '@/components/Landing'
import Books from '@/components/Books'
import About from '@/components/About'
import Contact from '@/components/Contact'


export default function Home() {
  return (
    <>
      <Head>
        <title>Odwa Bungu | Author</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navigation />
      <Landing />
      <Books />
      <About />
      <Contact />
    </>
  )
}
